name: Bug Report
description: Create a report to help us improve Paralux
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Steps to reproduce the behavior. Please provide a CodeSandbox or a minimal reproduction repository if possible.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Paralux version
      description: Which version of Paralux are you using?
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using? (e.g., Chrome, Safari, Firefox)
